name = "alteracaoproposta"
main = "functions/notion.js"
compatibility_date = "2024-01-01"
type = "javascript"

[build]
command = ""
cwd = "."

[env.production]
name = "alteracaoproposta"

