name = "alteracaoproposta"
pages_build_output_dir = "public"
compatibility_date = "2024-01-01"

vars = { NOTION_TOKEN = "ntn_d87800291735CSok9UAEgUkUBpPCLBjfwhuLV2HJG9c4cS", RESEND_API_KEY = "re_aX1Q9KXU_6R95aMWTnMwb6JquqntHhjab" }

[env.production]
name = "alteracaoproposta"
vars = { NOTION_TOKEN = "ntn_d87800291735CSok9UAEgUkUBpPCLBjfwhuLV2HJG9c4cS", RESEND_API_KEY = "re_aX1Q9KXU_6R95aMWTnMwb6JquqntHhjab" }

